apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycr1
rules:
- apiGroups: [""]  # Specifies the API group, "" refers to core API group (for resources like nodes, services, pvc)
  resources:
  - nodes
  - services
  - persistentvolumeclaims  # Use the full name for "pvc"
  verbs:
  - get
  - list
  - create
