apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: mypod
      labels:
        app: web
    spec:
      volumes:
        - name: s1
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: myc
          image: httpd
          volumeMounts:
            - mountPath: "/mnt/" 
              name: s1
