apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: testing
subjects:
  - kind: User
    name: mushahid
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: testing
  name: my-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myc
      image: vimal13/apache-webserver-php
      volumeMounts:
        - mountPath: /etc/httpd/config.d/
          name: mys1
  volumes:
    - configMap:
        name: mycm
      name: mys1