apiVersion: v1
kind: Pod
metadata:
  name: mydb
  labels:
    app: db
spec:
  containers:
    - name: mysql-con
      image: mysql:5.7
      volumeMounts:
        - mountPath: /var/lib/mysql/
          name: s1   
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "redhat"  
        - name: MYSQL_USER
          value: "myuser"
        - name: MYSQL_DATABASE
          value: "myapp"
        - name: MYSQL_PASSWORD
          value: "redhat"
    
          
  volumes:
    - name: s1
      persistentVolumeClaim:
        claimName: sql-pvc
